"""added faq model

Revision ID: 11afc1599481
Revises: 2d4c037ba021
Create Date: 2014-11-16 13:18:30.249207

"""

# revision identifiers, used by Alembic.
revision = '11afc1599481'
down_revision = '2d4c037ba021'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FAQs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=64), nullable=True),
    sa.Column('answer', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FAQs')
    ### end Alembic commands ###
