"""fixed mentor-student relationship

Revision ID: 1536f272c1e1
Revises: afa704a4f66
Create Date: 2014-10-26 18:01:07.761875

"""

# revision identifiers, used by Alembic.
revision = '1536f272c1e1'
down_revision = 'afa704a4f66'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('mentor_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'mentor_id')
    ### end Alembic commands ###
