"""empty message

Revision ID: 18ab4ae57f87
Revises: 3f890ed9b1d6
Create Date: 2014-12-04 21:55:00.796810

"""

# revision identifiers, used by Alembic.
revision = '18ab4ae57f87'
down_revision = '3f890ed9b1d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
