"""fixed add_student()

Revision ID: 1baf4db41dd9
Revises: 33186a7bc9f9
Create Date: 2014-10-26 18:08:33.822264

"""

# revision identifiers, used by Alembic.
revision = '1baf4db41dd9'
down_revision = '33186a7bc9f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
