"""empty message

Revision ID: 23be33dc600
Revises: 43221beb34b1
Create Date: 2014-12-05 02:15:13.620719

"""

# revision identifiers, used by Alembic.
revision = '23be33dc600'
down_revision = '43221beb34b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=64), nullable=True))
    op.create_index('ix_users_bio', 'users', ['bio'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_bio', 'users')
    op.drop_column('users', 'bio')
    ### end Alembic commands ###
