"""empty message

Revision ID: 2c77f2d1834d
Revises: 57f3eb66d719
Create Date: 2015-02-14 18:00:01.935437

"""

# revision identifiers, used by Alembic.
revision = '2c77f2d1834d'
down_revision = '57f3eb66d719'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
