"""added mentor functions

Revision ID: 2fca1dcec57b
Revises: 1536f272c1e1
Create Date: 2014-10-26 18:03:49.906988

"""

# revision identifiers, used by Alembic.
revision = '2fca1dcec57b'
down_revision = '1536f272c1e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
