"""fixed add_student()

Revision ID: 33186a7bc9f9
Revises: 2fca1dcec57b
Create Date: 2014-10-26 18:07:02.318400

"""

# revision identifiers, used by Alembic.
revision = '33186a7bc9f9'
down_revision = '2fca1dcec57b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
