"""added title to tasks and general_tasks

Revision ID: 357afe48914f
Revises: da3f591d0bb
Create Date: 2014-11-19 11:43:47.195113

"""

# revision identifiers, used by Alembic.
revision = '357afe48914f'
down_revision = 'da3f591d0bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general_tasks', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('title', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'title')
    op.drop_column('general_tasks', 'title')
    ### end Alembic commands ###
