"""added bio to user table

Revision ID: 383f7081b664
Revises: 1872f7473030
Create Date: 2014-12-05 01:24:29.315187

"""

# revision identifiers, used by Alembic.
revision = '383f7081b664'
down_revision = '1872f7473030'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=64), nullable=True))
    op.create_index('ix_users_bio', 'users', ['bio'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_bio', 'users')
    op.drop_column('users', 'bio')
    ### end Alembic commands ###
