"""empty message

Revision ID: 3dfc6bd1e328
Revises: 53a54516dc28
Create Date: 2014-11-16 12:05:26.920528

"""

# revision identifiers, used by Alembic.
revision = '3dfc6bd1e328'
down_revision = '53a54516dc28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
