"""empty message

Revision ID: 3f890ed9b1d6
Revises: 357afe48914f
Create Date: 2014-12-04 20:05:03.449577

"""

# revision identifiers, used by Alembic.
revision = '3f890ed9b1d6'
down_revision = '357afe48914f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed')
    ### end Alembic commands ###
