"""empty message

Revision ID: 41260040e02b
Revises: 250f0af7d943
Create Date: 2015-07-17 19:10:49.430393

"""

# revision identifiers, used by Alembic.
revision = '41260040e02b'
down_revision = '250f0af7d943'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('description', sa.String(length=5000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universities', 'description')
    ### end Alembic commands ###
