"""empty message

Revision ID: 43221beb34b1
Revises: 18ab4ae57f87
Create Date: 2014-12-04 22:47:00.253132

"""

# revision identifiers, used by Alembic.
revision = '43221beb34b1'
down_revision = '18ab4ae57f87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
