"""empty message

Revision ID: 4853d2c15233
Revises: 786262ba827
Create Date: 2014-11-02 15:11:41.986030

"""

# revision identifiers, used by Alembic.
revision = '4853d2c15233'
down_revision = '786262ba827'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
