"""empty message

Revision ID: 4aaae9936310
Revises: 575a1673a712
Create Date: 2014-11-16 14:43:30.333293

"""

# revision identifiers, used by Alembic.
revision = '4aaae9936310'
down_revision = '575a1673a712'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_contact', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_contact')
    ### end Alembic commands ###
