"""empty message

Revision ID: 50899eb52130
Revises: 239d2344f7fb
Create Date: 2014-11-09 14:48:41.427764

"""

# revision identifiers, used by Alembic.
revision = '50899eb52130'
down_revision = '239d2344f7fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
