"""empty message

Revision ID: 53a54516dc28
Revises: 50899eb52130
Create Date: 2014-11-16 11:58:34.935437

"""

# revision identifiers, used by Alembic.
revision = '53a54516dc28'
down_revision = '50899eb52130'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
