"""empty message

Revision ID: 57f3eb66d719
Revises: 23be33dc600
Create Date: 2014-12-05 03:22:34.224616

"""

# revision identifiers, used by Alembic.
revision = '57f3eb66d719'
down_revision = '23be33dc600'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
