"""empty message

Revision ID: 786262ba827
Revises: 43bfd9032e66
Create Date: 2014-11-02 14:41:19.229192

"""

# revision identifiers, used by Alembic.
revision = '786262ba827'
down_revision = '43bfd9032e66'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('university_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'university_id')
    ### end Alembic commands ###
