"""added mentor class

Revision ID: afa704a4f66
Revises: 3a67a15db324
Create Date: 2014-10-26 17:47:53.267084

"""

# revision identifiers, used by Alembic.
revision = 'afa704a4f66'
down_revision = '3a67a15db324'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mentors_email', 'mentors', ['email'], unique=True)
    op.create_index('ix_mentors_name', 'mentors', ['name'], unique=False)
    op.create_index('ix_mentors_number', 'mentors', ['number'], unique=True)
    op.create_index('ix_students_number', 'students', ['number'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_students_number', 'students')
    op.drop_index('ix_mentors_number', 'mentors')
    op.drop_index('ix_mentors_name', 'mentors')
    op.drop_index('ix_mentors_email', 'mentors')
    op.drop_table('mentors')
    ### end Alembic commands ###
