"""empty message

Revision ID: bb037d9a554
Revises: 41260040e02b
Create Date: 2015-07-17 19:28:58.886650

"""

# revision identifiers, used by Alembic.
revision = 'bb037d9a554'
down_revision = '41260040e02b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
