"""empty message

Revision ID: da3f591d0bb
Revises: 11afc1599481
Create Date: 2014-11-16 15:01:33.440546

"""

# revision identifiers, used by Alembic.
revision = 'da3f591d0bb'
down_revision = '11afc1599481'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_phone', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_phone')
    ### end Alembic commands ###
